class InvalidAttributeException(Exception):' Raised when provided attribute is invalid. '
class InvalidAudienceException(Exception):' Raised when provided audience is invalid. '
class InvalidEventException(Exception):' Raised when provided event key is invalid. '
class InvalidEventTagException(Exception):' Raised when provided event tag is invalid. '
class InvalidExperimentException(Exception):' Raised when provided experiment key is invalid. '
class InvalidGroupException(Exception):' Raised when provided group ID is invalid. '
class InvalidInputException(Exception):' Raised when provided datafile, event dispatcher, logger, event processor or error handler is invalid. '
class InvalidVariationException(Exception):' Raised when provided variation is invalid. '
class UnsupportedDatafileVersionException(Exception):' Raised when provided version in datafile is not supported. '